### ISSUE TITLE
problem in installing IntaRNA

### ISSUE THREAD

**Issue by NWAFU-daniel** [BackofenLab/IntaRNA#41]
Making all in src
make[1]: Entering directory '/home/daniel/downloads/IntaRNA/src'
g++ -DPACKAGE_NAME=\"IntaRNA\" -DPACKAGE_TARNAME=\"intarna\" -DPACKAGE_VERSION=\"1.2.5\" -DPACKAGE_STRING=\"IntaRNA\ 1.2.5\" -DPACKAGE_BUGREPORT=\"intarna@informatik.uni-freiburg.de\" -DPACKAGE_URL=\"\" -DPACKAGE=\"intarna\" -DVERSION=\"1.2.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DNDEBUG=1 -I.     -O2 -g -O2 -MT basics.o -MD -MP -MF .deps/basics.Tpo -c -o basics.o basics.cpp
In file included from /usr/include/ViennaRNA/data_structures.h:157:0,
                 from /usr/include/ViennaRNA/fold.h:4,
                 from basics.h:28,
                 from basics.cpp:1:
/usr/include/ViennaRNA/params.h:445:1: error: ambiguating new declaration of ‘vrna_param_t* scale_parameters()’
 DEPRECATED(vrna_param_t *scale_parameters(void));
 ^
In file included from basics.h:19:0,
                 from basics.cpp:1:
energy.h:10:8: note: old declaration ‘void scale_parameters()’
 void   scale_parameters();
        ^
Makefile:295: recipe for target 'basics.o' failed
make[1]: *** [basics.o] Error 1
make[1]: Leaving directory '/home/daniel/下载/IntaRNA/src'
Makefile:238: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@y460:/home/daniel/downloads/IntaRNA#

**Comment by martin-mann** [comment]
I am quite sure you are compiling IntaRNA agains Vienna RNA package 2.*

Currently, you have to use an old [Vienna package version = 1.8.5](http://www.tbi.univie.ac.at/RNA/download/sourcecode/1_8_x/ViennaRNA-1.8.5.tar.gz) !!! 

Please 
- follow the link
- download, compile, and install VRNA 1.8.5
- recompile IntaRNA 1.2.5 using VRNA 1.8.5

We are currently working on IntaRNA 2.0 that will use the recent VRNA package. Meanwhile, please follow the given description!
